_wandb:
    value:
        cli_version: 0.23.1
        e:
            x7cpuejnhln6ynj5wyhceudd8d7mop80:
                cpu_count: 12
                cpu_count_logical: 16
                disk:
                    /:
                        total: "509722226688"
                        used: "397520195584"
                email: ahp9@hi.is
                executable: C:\Users\astri\AppData\Local\Programs\Python\Python314\python.exe
                git:
                    commit: 1ca2fb2965c003a4ec8188137f9f651192e064d8
                    remote: https://github.com/ahp9/new_project_mlops.git
                host: DESKTOP-98E2PN1
                memory:
                    total: "16890978304"
                os: Windows-11-10.0.26200-SP0
                program: -m __main__
                python: CPython 3.14.2
                root: C:\Users\astri\Documents\DTU\3.Ã¶nn\ML Ops\Cookiecutter\new_project_mlops
                startedAt: "2026-01-08T10:12:50.710731Z"
                writerId: x7cpuejnhln6ynj5wyhceudd8d7mop80
        m: []
        python_version: 3.14.2
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 16
            "4": 3.14.2
            "5": 0.23.1
            "8":
                - 3
            "12": 0.23.1
            "13": windows-amd64
batch_size:
    value: 64
epochs:
    value: 10
learning_rate:
    value: 0.001
